HRM_SYS/HRM_SYS/urls.py
from django.contrib import admin
from django.urls import path,include 
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_view
from django.conf import settings

urlpatterns = [
    path('admin', admin.site.urls),
    path('login',auth_view.LoginView.as_view(template_name = 'management/login.html'),name="login"),
    path('logout/',auth_view.LoginView.as_view(template_name='management/logout.html'),name="logout"),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_view.PasswordResetConfirmView.as_view(template_name='management/password_reset_confirm.html'),
         name='password_reset_confirm'),
         path('password-reset-complete/',
         auth_view.PasswordResetCompleteView.as_view(template_name='management/password_reset_complete.html'),
         name='password_reset_complete'),
    path('',include('management.urls')),
    path('',include('payroll.urls')),
    path('',include('hrm_users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)


admin.site.site_header = 'Beezy'                    # default: "Django Administration"
admin.site.index_title = 'Admin page'                 # default: "Site administration"
admin.site.site_title = 'Beezy admin'

HRM_SYS/payroll/urls.py
from django.urls import path 
from . import views 
from .views import gen_payroll,monthly_payroll,gen_payslip,payroll_details,\
      payroll_check,grouped_payroll,EditPayrollView,re_calculate,email_payroll,\
            payroll_sum,add_extra_payments,gen_extra_payement_temp,import_extra_payments,flat_payroll,grouping,payroll_action


urlpatterns = [
     
      path('reports',views.gen_payroll,name="payroll-reports"),
      path('monthly_payroll',views.monthly_payroll,name="payroll-month"),
      path('flat_payroll',views.flat_payroll,name="payroll-flat"),
      path('payslip/<str:signid>',views.gen_payslip,name="payroll-payslip"),
      path('payroll_details',views.payroll_details,name="payroll-details"),
      path('payroll_check',views.payroll_check,name="payroll-check"),
      path('payroll_action',views.payroll_action,name="payroll-action"),
      path('payroll_re_calculate',views.re_calculate,name="payroll-re-calculate"),
      path('grouped_payroll',views.grouped_payroll,name="payroll-grouped"),
      path('grouping_payroll',views.grouping,name="payroll-grouping"),
      path('email_payroll',views.email_payroll,name="payroll-email"),
      path('add_extra_payments',views.add_extra_payments,name="payroll-extra-payments"),
      path('extra_payments_template',views.gen_extra_payement_temp,name="payroll-extra-payments-temp"),
      path('import_extra_payments',views.import_extra_payments,name="payroll-extra-payments-import"),
      path('summary/<str:payroll_id>',views.payroll_sum,name="payroll-summary"),
      path('edit_payroll/<int:pk>',EditPayrollView.as_view(),name="payroll-edit-payroll"),

]

HRM_SYS/payroll/models.py
from django.db import models
from django.utils import timezone

import datetime

# Create your models here.

class PayRoll(models.Model):
    org_name = models.CharField(max_length=100,null=True)
    payroll_id = models.CharField(max_length=100,null=True)
    employee_id = models.CharField(max_length=100,null=True)
    sign_id = models.CharField(max_length=100,null=True)
    name = models.CharField(max_length=100,null=True)
    id_no = models.CharField(max_length=100,null=True)
    pin_no = models.CharField(max_length=100,null=True)
    phone = models.CharField(max_length=100,null=True)
    role = models.CharField(max_length=100,null=True)
    account_no = models.CharField(max_length=100,null=True)
    basic_salary = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    allowance =  models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    add_ons = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    total_days = models.FloatField(default=0.0)
    overtime_hours = models.FloatField(default=0.0)
    overtime_pay = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    incentives = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    leave_days = models.FloatField(default=0.0)
    deductions = models.DecimalField(default=0.00,max_digits=10,decimal_places=2) 
    gross_pay  = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    taxable_income = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    tax = models.DecimalField(default=0.00,max_digits=10,decimal_places=2) 
    nhif = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    nssf = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    insurance = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    housing = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    loan_deductions = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    welfare_deductions = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    others = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    net_pay = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    created_date = models.DateField(default=timezone.now)
    created_time = models.TimeField(default=timezone.now)
    status = models.CharField(max_length=100,default="audit")
    pay_run = models.CharField(max_length=200,default='')
 

    def __str__(self):

        return self.payroll_id

tax_formula = '''24000=10,8333=25,467667=30,300000=32.5'''
class PayRollSetting(models.Model):
    
    org_name = models.CharField(max_length=100,default="")
    category = models.CharField(max_length=100)
    tax_rate = models.TextField(default=tax_formula)
    relief = models.DecimalField(default=2400.00,max_digits=10,decimal_places=2)
    nssf = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
   


    def __str__(self):

        return self.category

class ExtraPayments(models.Model):

    employee_id = models.CharField(max_length=100)
    overtime_hours = models.FloatField(default=0.0)
    overtime_rate = models.FloatField(default=0.0)
    incentive = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    performance = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    awards = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    loan_deductions = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    welfare_deductions = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    unpaid_leave_deductions = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    modified_absentee_deductions = models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    created = models.DateTimeField(default=timezone.now)


    def __str__(self):

        return self.employee_id

class Payroll_Rates(models.Model):

    nhif_rates_file = models.FileField(upload_to='nhif_files')
    nhif_relief_rate = models.FloatField(default=15.0)
    nssf_rate = models.FloatField(default=6.0)
    house_levy_rate = models.FloatField(default=1.5)
    paye_rates = models.FileField(upload_to='paye_files')
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):

        return str(self.created)

HRM_SYS/payroll/forms.py
from django import forms 
from .models import ExtraPayments 

class ExtraPaymentsForm(forms.ModelForm):

    class Meta:

        model = ExtraPayments 
        fields = "__all__"

HRM_SYS/payroll/views.py
from django.shortcuts import render
from django.http import JsonResponse,FileResponse
from django.contrib import messages
from django.views.generic import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.template.loader import render_to_string,get_template
from django.core.mail import EmailMultiAlternatives
from django.core.mail import EmailMessage
from django.db.models import Sum,Count
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.cache import cache_page
from .forms import ExtraPaymentsForm
from management.models import * 
from .formula import tax_amount,nhif_pay,nssf_pay,house_levy_pay,nhif_relief
from .temps import gen_temp
from .models import *
import datetime
from datetime import datetime,date, timedelta
import pandas as pd
import json
from decimal import Decimal

import math
import pytz
import os
# Create your views here.


def gen_payroll(request):
    

    settings = PayRollSetting.objects.all()

    payroll_report = PayRoll.objects.all().order_by('-pk')

    grouped_payroll = PayRoll.objects.values('payroll_id').annotate(size = Count('employee_id'),total_amount=Sum('gross_pay'))

    context = {"payrolls":payroll_report,"by_payroll_ids":grouped_payroll,"settings":settings,"extra_payment_form":ExtraPaymentsForm}

    return render(request,"payroll/reports.html",context)

def monthly_payroll(request):
    utc=pytz.UTC
    if request.POST:
        date1 = request.POST.get("date1")
        date2 = request.POST.get("date2")
        payroll_id = request.POST.get("payId")
      
        
        date2 = utc.localize(datetime.strptime(date2, '%Y-%m-%d')+timedelta(days=1))
        date1 = utc.localize(datetime.strptime(date1, '%Y-%m-%d'))
        
        
        payrolls = []
        for employee in Employee.objects.all():
            
            
            attendances = Attendance.objects.filter(employee=employee).filter(created__range = [date1,date2])
            if len(attendances) > 0:
               
                total_hours,expected_hours,deductions,leave_days,gross_pay,net_pay,days = 0,0,0,0,0,0,0
                for attendance in attendances:

                    total_hours += attendance.hours
                    
                    days += attendance.days
                leave_days += sum([leave.days for leave in Applications.objects.filter(applicant=User.objects.get(username=employee.emp_id)).filter(type__name = "leave") if leave.status=="complete"])

                overtime_hours = sum([i.overtime_hours for i in ExtraPayments.objects.filter(employee_id = employee.emp_id) if i.created >= date1 and i.created <= date2 ])

                overtime_pay = sum([(i.overtime_hours * i.overtime_rate) for i in ExtraPayments.objects.filter(employee_id = employee.emp_id) if i.created >= date1 and i.created <= date2])
                if str(overtime_pay).isdecimal()==False:
                    overtime_pay = 0.00
                
                incentives  = sum([i.incentive for i in ExtraPayments.objects.filter(employee_id = employee.emp_id) if i.created >= date1 and i.created <= date2])
                print(incentives)
                if str(incentives).isdecimal() ==False:
                    incentives = 0.00
                
                loan_deductions = sum([i.loan_deductions for i in ExtraPayments.objects.filter(employee_id = employee.emp_id) if i.created >= date1 and i.created <= date2])
                if str(loan_deductions).isdecimal() == False:
                    loan_deductions = 0.00
                
                welfare_deductions = sum([i.welfare_deductions for i in ExtraPayments.objects.filter(employee_id = employee.emp_id) if i.created >= date1 and i.created <= date2])
                if str(welfare_deductions).isdecimal == False:
                    welfare_deductions == 0.00
                
                try:
                    deductions = Decimal(((AttSettings.objects.get(employee_id=employee.emp_id).expected_days)-days)*AttSettings.objects.get(employee_id=employee.emp_id).deduction_per_day)
                except:
                    deductions = 0.00
                
                if math.isnan(employee.salary)==True:
                    salary = 0.00
                    gross_pay = Decimal(0.00+incentives+overtime_pay)
                
                else:
                    salary = employee.salary
                    gross_pay = Decimal(employee.salary+incentives+overtime_pay)
                
                nhif = nhif_pay(gross_pay)

                nssf = employee.payroll_settings.nssf

                house_levy = house_levy_pay(gross_pay)
        
                taxable_income  = Decimal(Decimal(gross_pay)-(nssf))

                tax =  Decimal(tax_amount(employee.payroll_settings.tax_rate,taxable_income,employee.payroll_settings.relief))
                
                nhif_relf = Decimal(nhif_relief(nhif,tax))

                tax = tax-nhif_relf

                

                net_pay = gross_pay-Decimal(nssf)\
                        -tax\
                        -Decimal(nhif)-Decimal(house_levy)-Decimal(deductions)-Decimal(loan_deductions)-Decimal(welfare_deductions)
                
                data = {
                    "org_name":employee.payroll_settings.org_name,
                    "payroll_id":payroll_id,
                    "employee_id":employee.emp_id,
                    "sign_id":str(payroll_id)+str(employee.emp_id),
                    "name":str(employee.first_name)+" "+ str(employee.second_name),
                    "id_no":employee.national_no,
                    "pin_no":employee.kra_pin,
                    "phone":employee.phone,
                    "role":employee.role,
                    "account_no":employee.account_no,
                    "basic_salary":salary,
                    #"allowance":employee.allowance,
                    "overtime_pay":overtime_pay,
                    "overtime_hours":overtime_hours,
                    "incentives":incentives,
                    #"add_ons":employee.add_ons,
                    "total_days":days,
                    "leave_days":leave_days,
                    "deductions":deductions,
                    "loan_deductions":loan_deductions,
                    "welfare_deductions":welfare_deductions,
                    "gross_pay":gross_pay,
                    "taxable_income":taxable_income,
                    "tax": tax,
                    "nhif":nhif,
                    "nssf":nssf,
                    
                    "housing": house_levy,
                   
                    "net_pay":net_pay,
                    
                    "created_date": datetime.now(),
                    "created_time":datetime.now(),
                    "pay_run": str(date1)+" - "+str(date2)
                    


                }
                payrolls.append(data)
           
                
            else:

                JsonResponse("no data to process",safe=False)
                
   
        for payroll in payrolls:

            pay = PayRoll(**payroll)
            pay.save()

        return JsonResponse(json.dumps(payrolls,default=str),safe=False)

def gen_payslip(request,signid):
    
    emp_payroll = PayRoll.objects.get(sign_id=signid)

  

    context = {"details":emp_payroll}

    return render(request,'payroll/payslip.html',context)


def payroll_details(request):

    if request.POST:

        id = request.POST.get("id")
    
        details = PayRoll.objects.filter(payroll_id=id)
        
        cost,size,org= 0,0,[]
        payrolls,created = [],[]
        for detail in details:

            info = {
                "employee_id":detail.employee_id,
                "name":detail.name,
                "pin_no":detail.pin_no,
                "taxable":detail.taxable_income,
                "gross_pay":detail.gross_pay,
                "paye":detail.tax,
                "net_pay":detail.net_pay,
                "created":detail.created_date,
            }
            cost+=detail.gross_pay
            size+=1
            org.append(detail.org_name)
            created.append(detail.created_date)

           

            payrolls.append(info)
        summary = {"cost":cost,"size":size,"org":org,"created":created[0]}
       
        return JsonResponse(json.dumps(summary,default=str),safe=False)
    
def payroll_check(request):

    if request.POST:

        id = request.POST.get("id")
     

        payrolls = PayRoll.objects.filter(payroll_id = id)
        for payroll in payrolls:

            payroll.status = "audited"

            payroll.save()

        return JsonResponse("audit completed",safe=False)


'''  
    ===================================================================================
        create view where payroll master can change info manually
'''

def grouped_payroll(request):

    grouped_payroll = PayRoll.objects.values('payroll_id').annotate(size = Count('employee_id'),total_amount=Sum('gross_pay'))

    context = {"by_payroll_ids":grouped_payroll}

    return render(request,'payroll/grouped_table.html',context)

def email_payroll(request):

    if request.POST:

        payroll_id = request.POST.get("payroll_id")
        payrolls = PayRoll.objects.filter(payroll_id = payroll_id)
        
        for payroll in payrolls:

            subject = payrolls[0].org_name + " payroll "+payrolls[0].pay_run

            

            html_body = render_to_string("payroll/payslip.html",{ 'details': PayRoll.objects.get(sign_id=payroll.sign_id)} )

            message = EmailMultiAlternatives(
            subject=subject,
            body="",
            from_email="koshtech.site@gmail.com",
            to=[Employee.objects.get(emp_id = payroll.employee_id).email]
            )
            message.attach_alternative(html_body, "text/html")
            message.send(fail_silently=False)

HRM_SYS/payroll/templates/payroll/edit_payroll.html
{% extends 'management/base2.html' %}
{% load crispy_forms_tags %}

{% block content %}
     <!-- create camera modal here-->
      <!-- partial -->
<div class="main-panel">        
      <div class="content-wrapper">
          <div class="row">
            
           
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">payroll personal info</h4>
                    <form class="form-sample" method="POST">
                      {% csrf_token %}
                      <p class="card-description">
                        Personal info
                      </p>
                      <div class="row">
                        {% for field in form %}
                        <div class="col-md-6">
                          <div class="form-group row">
                           
                            <div class="col-sm-9">
                              {{field | as_crispy_field}}
                            </div>
                          </div>
                        </div>
                        {% endfor %}
                        
                      </div>
                      
                      <button type="submit" class="btn btn-primary mr-2">Edit</button>
                      
                    </form>
                    <br>
                    <button type="button" class="btn btn-success mr-2" onclick="Calculate()">Re-Calculate</button>
                    
                  </div>
                </div>
          
            
          </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:../../partials/_footer.html -->
       
        <!-- partial -->
      </div>

    <script>
     
     function Calculate(){
         
      alert($("#id_org_name").val())
         $.ajax({
           
            type:"POST",
            url:"{% url 'payroll-re-calculate' %}",
            data:{
               
              org_name:$("#id_org_name").val(),
              sign_id:$("#id_sign_id").val(),
              pin_no:$("#id_pin_no").val(),
              basic_salary: $("#id_basic_salary").val(),
              allowance:$("#id_allowance").val(),
              add_ons:$("#id_add_ons").val(),
              total_hours:$("#id_total_days").val(),
              leave_days:$("#id_leave_days").val(),
              deductions:$("#id_deductions").val(),
              nhif:$("#id_nhif").val(),
              nssf:$("#id_nssf").val(),
              insurance:$("#id_insurance").val(),
              housing:$("#id_housing").val(),
              others:$("#id_others").val(),
              overtime_hours:$("#id_overtime_hours").val(),
              overtime_pay:$("#id_overtime_pay").val(),
              incentives:$("#id_incentives").val(),
              welfare:$("#id_welfare_deductions").val(),
              loan:$("#id_loan_deductions").val(),
     
    

              csrfmiddlewaretoken:'{{ csrf_token }}'
                
            },
            success:function(data,status){
                
                alert(data)
            }
             
         })
     }

    </script>
  {% endblock content %}

  

HRM_SYS/payroll/templates/payroll/grouped_table.html
<table  class="table table-striped"  id="paygen" style="zoom: 100%; font-weight: bolder;">
    <thead style="background-color: yellowgreen;">
        <tr>
            <th>payroll id</th>
            <th>total payable</th>
            <th>size</th>
            <th>created</th>
            <th>view all</th>
            <th>Action</th>
          
            
           
           
        </tr>
    </thead>
    <tbody>
        {% for payroll in by_payroll_ids  %}
        <tr>
            <td>{{payroll.payroll_id}}</td>
            <td>{{payroll.total_amount}}</td>
            <td>{{payroll.size}}</td>
            <td>{{payroll.created_date}} {{payroll.created_time}}</td>
            <td><a class="btn btn-primary" onclick="showDetails('{{payroll.payroll_id}}')"><i class="ti-check"></i></a></td>
            <td><a><i class="fa fa-envelope"></i>email</a></td>
           
        </tr>
        {% endfor %}
  

HRM_SYS/payroll/templates/payroll/summary.html
{% load mathfilters %}
<html>
	<head>
<style>
    body {
	background: #f0f0f0;
	width: 100vw;
	height: 100vh;
	display: flex;
	justify-content: center;
    padding: 20px;
    height: 100%;
}

@import url('https://fonts.googleapis.com/css?family=Roboto:200,300,400,600,700');

* {
	font-family: 'Roboto', sans-serif;
	font-size: 12px;
	color: #444;
}

#payslip {
	width: calc( 8.5in - 80px );
	height: calc( 11in - 60px );
	background: #fff;
	padding: 30px 40px;
}

#title {
	margin-bottom: 20px;
	font-size: 38px;
	font-weight: 600;
}

#scope {
	border-top: 1px solid #ccc;
	border-bottom: 1px solid #ccc;
	padding: 7px 0 4px 0;
	display: flex;
	justify-content: space-around;
}

#scope > .scope-entry {
	text-align: center;
}

#scope > .scope-entry > .value {
	font-size: 14px;
	font-weight: 700;
}

.content {
	display: flex;
	border-bottom: 1px solid #ccc;
	height: 880px;
}

.content .left-panel {
	border-right: 1px solid #ccc;
	min-width: 200px;
	padding: 20px 16px 0 0;
}

.content .right-panel {
	width: 100%;
	padding: 10px 0  0 16px;
}

#employee {
	text-align: center;
	margin-bottom: 20px;
}
#employee #name {
	font-size: 15px;
	font-weight: 700;
}

#employee #email {
	font-size: 11px;
	font-weight: 300;
}

.details, .contributions, .ytd, .gross {
	margin-bottom: 20px;
}

.details .entry, .contributions .entry, .ytd .entry {
	display: flex;
	justify-content: space-between;
	margin-bottom: 6px;
}

.details .entry .value, .contributions .entry .value, .ytd .entry .value {
	font-weight: 700;
	max-width: 130px;
	text-align: right;
}

.gross .entry .value {
	font-weight: 700;
	text-align: right;
	font-size: 16px;
}

.contributions .title, .ytd .title, .gross .title {
	font-size: 15px;
	font-weight: 700;
	border-bottom: 1px solid #ccc;
	padding-bottom: 4px;
	margin-bottom: 6px;
}

.content .right-panel .details {
	width: 100%;
}

.content .right-panel .details .entry {
	display: flex;
	padding: 0 10px;
	margin: 6px 0;
}

.content .right-panel .details .label {
	font-weight: 700;
	width: 120px;
}

.content .right-panel .details .detail {
	font-weight: 600;
	width: 130px;
}

.content .right-panel .details .rate {
	font-weight: 400;
	width: 80px;
	font-style: italic;
	letter-spacing: 1px;
}

.content .right-panel .details .amount {
	text-align: right;
	font-weight: 700;
	width: 90px;
}

.content .right-panel .details .net_pay div, .content .right-panel .details .nti div {
	font-weight: 600;
	font-size: 12px;
}

.content .right-panel .details .net_pay, .content .right-panel .details .nti {
	padding: 3px 0 2px 0;
	margin-bottom: 10px;
	background: rgba(0, 0, 0, 0.04);
}

</style>
	</head>
<div id="payslip">
	<div id="title">{{org}}</div>
	<div id="scope">
		<div class="scope-entry">
			<div class="title">PAY RUN</div>
			<div class="value">{{payrun}}</div>
		</div>
		<div class="scope-entry">
			<div class="title">PAY PERIOD</div>
			<div class="value">{{details.pay_run}}</div>
		</div>
	</div>
	<div class="content" >
		<div class="right-panel">
			<div class="details">
                <div class="nti" >
					<div class="entry">
						<div class="label">PAYABLES</div>
						
					</div>
				</div>
				<div class="basic-pay">
					<div class="entry">
						<div class="label">Total Basic Pay</div>
						<div class="detail"></div>
						
						<div class="amount">{{summary.salary}}</div>
					</div>
				</div>
			
				<div class="leaves">
					<div class="entry">
						<div class="label">Total Earnings</div>
						<div class="detail"></div>
						<div class="rate"></div>
						<div class="amount"></div>
					</div>
					<div class="entry paid">
						<div class="label"></div>
						<div class="detail">Allowance</div>
						<div class="rate"></div>
						<div class="amount">{{summary.allowance}}</div>
					</div>
					<div class="entry unpaid">
						<div class="label"></div>
						<div class="detail">Overtime</div>
						<div class="rate"></div>
						<div class="amount">{{summary.overtime}}</div>
					</div>
				</div>
				<div class="taxable_allowance">
					<div class="entry">
						<div class="label"></div>
						<div class="detail">Incentives</div>
						<div class="rate"></div>
						<div class="amount">{{summary.incentives}}</div>
					</div>
					<div class="entry">
						<div class="label"></div>
						<div class="detail">Add ons</div>
						<div class="rate"></div>
						<div class="amount">{{summary.add_ons}}</div>
					</div>
				</div>
                <div class="nti">
					<div class="entry">
						<div class="label">Total Gross Pay</div>
						<div class="detail"></div>
						<div class="rate"></div>
						<div class="amount">{{summary.gross}}</div>
					</div>
				</div>
				
				<div class="taxable_commission"></div>
				<div class="contributions">
					<div class="entry">
						<div class="label">Total Contributions</div>
						<div class="detail"></div>
						<div class="rate"></div>
						<div class="amount"></div>
					</div>
					<div class="entry">
						<div class="label"></div>
						<div class="detail">NSSF</div>
						<div class="rate"></div>
						<div class="amount">{{summary.nssf}}</div>
					</div>
					<div class="entry">
						<div class="label"></div>
						<div class="detail">NHIF</div>
						<div class="rate"></div>
						<div class="amount">{{summary.nhif}}</div>
					</div>
					<div class="entry">
						<div class="label"></div>
						<div class="detail">housing</div>
						<div class="rate"></div>
						<div class="amount">{{summary.housing}}</div>
					</div>
					<div class="entry">
						<div class="label"></div>
						<div class="detail">Insurance</div>
						<div class="rate"></div>
						<div class="amount">{{summary.insurance}}</div>
					</div>
					<div class="entry">
						<div class="label"></div>
						<div class="detail">welfare</div>
						<div class="rate"></div>
						<div class="amount">{{summary.welfare}}</div>
					</div>
				</div>
				<div class="nti">
					<div class="entry">
						<div class="label">PAYE</div>
						<div class="detail"></div>
						<div class="rate"></div>
						<div class="amount">{{summary.tax}}</div>
					</div>
				</div>
				<div class="withholding_tax">
					<div class="entry">
						<div class="label">PAYE</div>
						<div class="detail"></div>
						<div class="rate"></div>
						<div class="amount">({{details.tax}})</div>
					</div>
				</div>
               
				
				<div class="non_taxable_bonus">
					<div class="entry">
						<div class="label">Deductions</div>
						<div class="detail"></div>
						<div class="rate"></div>
						<div class="amount"></div>
					</div>
					<div class="entry">
						<div class="label"></div>
						<div class="detail">Absent deductions</div>
						<div class="rate"></div>
						<div class="amount">{{summary.deductions}}</div>
					</div>
				</div>
				<div class="non_taxable_commission">
					<div class="entry">
						<div class="label"></div>
						<div class="detail">Loan deductions</div>
						<div class="rate"></div>
						<div class="amount">{{summary.loan}}</div>
					</div>
					<div class="entry">
						<div class="label"></div>
						<div class="detail">Others</div>
						<div class="rate"></div>
						<div class="amount">{{summary.others}}</div>
					</div>
					
				</div>
				
				<div class="net_pay">
					<div class="entry">
						<div class="label">Total</div>
						<div class="detail"></div>
						<div class="rate"></div>
						<div class="amount">{{summary.gross|sub:summary.deductions|sub:summary.loan|sub:summary.others}}</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</html>